version: 2
updates:
  - package-ecosystem: gomod
    directory: /apps/api
    schedule:
      interval: monthly
    groups:
      go-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: monthly
    groups:
      npm-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
